### ISSUE TITLE
assignment3 problem

### ISSUE THREAD

**Issue by Jack-An** [veraposeidon/CS131_Assignments#1]
关键点匹配的时候，你的那个匹配结果你会发现有一个匹配结果是将左图的树和右图的房子对应起来了。

**Comment by Jack-An** [comment]
计算response的时候，你没有给矩阵的迹平方，我加上后就没问题了。

**Comment by veraposeidon** [comment]
@Jack-An 你说的对，要给迹加平方。R=Det(M)-k(Trace(M)^2)。
